# Generated by Django 4.2.28 on 2026-02-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
    ]
